name: Build-Debug

on:
  push:
    branches:
      - "main"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - main

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Install Nats Server
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go build main.go
          mkdir -p ~/.local/bin
          cp main ~/.local/bin/nats-server
          cd ..
          rm -rf nats-server
          nats-server -v
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build < /dev/null
